version: "2"

run:
  timeout: 5m

linters:
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    
    govet:
      enable:
        - shadow
        - printf
    
    revive:
      severity: warning
      rules:
        - name: exported
        - name: var-naming
        - name: error-naming
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: receiver-naming
        - name: unreachable-code
    
    goconst:
      min-len: 3
      min-occurrences: 2
    
    misspell:
      locale: US
    
    gosec:
      excludes:
        - G404
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - goconst
    - misspell
    - gosec
    - bodyclose
    - sqlclosecheck

formatters:
  settings:
    gofmt:
      simplify: true

  enable:
    - gofmt
    - goimports

issues:  
  max-issues-per-linter: 50
  max-same-issues: 10